import React from "react";
import { MainLayout } from "@/components/layout/main-layout";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export default function Reports() {
  return (
    <MainLayout title="Reports">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-semibold text-neutral-800">Reports</h1>
          <p className="text-neutral-500">Generate and view business reports</p>
        </div>
        <Button>
          <i className="fas fa-file-export mr-2"></i> Export Report
        </Button>
      </div>
      
      {/* Report Categories */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
        <Card className="hover:shadow-md transition-shadow">
          <CardContent className="p-6">
            <div className="flex flex-col items-center text-center">
              <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center text-primary mb-4">
                <i className="fas fa-chart-line text-xl"></i>
              </div>
              <h3 className="font-semibold text-lg mb-2">Sales Reports</h3>
              <p className="text-neutral-500 text-sm mb-4">View detailed sales analysis, trends, and performance metrics</p>
              <Button variant="outline" size="sm">Generate Report</Button>
            </div>
          </CardContent>
        </Card>
        
        <Card className="hover:shadow-md transition-shadow">
          <CardContent className="p-6">
            <div className="flex flex-col items-center text-center">
              <div className="w-16 h-16 rounded-full bg-info/10 flex items-center justify-center text-info mb-4">
                <i className="fas fa-cubes text-xl"></i>
              </div>
              <h3 className="font-semibold text-lg mb-2">Inventory Reports</h3>
              <p className="text-neutral-500 text-sm mb-4">Track stock levels, valuation, and inventory movement</p>
              <Button variant="outline" size="sm">Generate Report</Button>
            </div>
          </CardContent>
        </Card>
        
        <Card className="hover:shadow-md transition-shadow">
          <CardContent className="p-6">
            <div className="flex flex-col items-center text-center">
              <div className="w-16 h-16 rounded-full bg-warning/10 flex items-center justify-center text-warning mb-4">
                <i className="fas fa-money-bill-wave text-xl"></i>
              </div>
              <h3 className="font-semibold text-lg mb-2">Financial Reports</h3>
              <p className="text-neutral-500 text-sm mb-4">Access profit & loss statements, expense analysis, and more</p>
              <Button variant="outline" size="sm">Generate Report</Button>
            </div>
          </CardContent>
        </Card>
      </div>
      
      {/* Recent Reports */}
      <Card>
        <CardContent className="p-6">
          <h2 className="text-lg font-semibold mb-4">Recent Reports</h2>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b">
                  <th className="text-left py-3 px-4">Report Name</th>
                  <th className="text-left py-3 px-4">Type</th>
                  <th className="text-left py-3 px-4">Generated On</th>
                  <th className="text-left py-3 px-4">Generated By</th>
                  <th className="text-right py-3 px-4">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b hover:bg-neutral-50">
                  <td className="py-3 px-4 font-medium">Monthly Sales Summary</td>
                  <td className="py-3 px-4">Sales</td>
                  <td className="py-3 px-4">May 15, 2023</td>
                  <td className="py-3 px-4">Admin</td>
                  <td className="py-3 px-4 text-right">
                    <Button variant="outline" size="sm" className="mr-2">
                      <i className="fas fa-eye mr-1"></i> View
                    </Button>
                    <Button variant="outline" size="sm">
                      <i className="fas fa-download mr-1"></i> Download
                    </Button>
                  </td>
                </tr>
                <tr className="border-b hover:bg-neutral-50">
                  <td className="py-3 px-4 font-medium">Quarterly Inventory Valuation</td>
                  <td className="py-3 px-4">Inventory</td>
                  <td className="py-3 px-4">Apr 1, 2023</td>
                  <td className="py-3 px-4">Admin</td>
                  <td className="py-3 px-4 text-right">
                    <Button variant="outline" size="sm" className="mr-2">
                      <i className="fas fa-eye mr-1"></i> View
                    </Button>
                    <Button variant="outline" size="sm">
                      <i className="fas fa-download mr-1"></i> Download
                    </Button>
                  </td>
                </tr>
                <tr className="border-b hover:bg-neutral-50">
                  <td className="py-3 px-4 font-medium">Annual Financial Statement</td>
                  <td className="py-3 px-4">Financial</td>
                  <td className="py-3 px-4">Jan 10, 2023</td>
                  <td className="py-3 px-4">Admin</td>
                  <td className="py-3 px-4 text-right">
                    <Button variant="outline" size="sm" className="mr-2">
                      <i className="fas fa-eye mr-1"></i> View
                    </Button>
                    <Button variant="outline" size="sm">
                      <i className="fas fa-download mr-1"></i> Download
                    </Button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </MainLayout>
  );
}